# Generated by Django 5.2.5 on 2025-09-01 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par +2135, +2136 ou +2137 et contenir 9 chiffres après', regex='^\\+213(5|6|7)[0-9]{8}$')]),
        ),
    ]
