# Generated by Django 5.2.5 on 2025-08-13 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text="Identifiant unique pour ce tableau (ex: 'projects', 'users')", max_length=255, unique=True, verbose_name='Endpoint')),
                ('display_name', models.CharField(help_text="Nom lisible du tableau (ex: 'Liste des projets')", max_length=255, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Description du tableau pour les utilisateurs', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Configuration',
                'verbose_name_plural': 'Table Configurations',
            },
        ),
        migrations.CreateModel(
            name='HeaderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Clé du champ (ex: 'start_date')", max_length=255, verbose_name='Field Key')),
                ('display_name', models.CharField(help_text="Nom d'affichage pour l'en-tête", max_length=255, verbose_name='Display Name')),
                ('help_text', models.TextField(blank=True, help_text='Description du champ', null=True, verbose_name='Help Text')),
                ('field_type', models.CharField(default='text', help_text='Type de données (text, date, boolean, etc.)', max_length=50, verbose_name='Field Type')),
                ('sortable', models.BooleanField(default=True, help_text='Peut être trié ou non', verbose_name='Sortable')),
                ('visible', models.BooleanField(default=True, help_text='Visible par défaut dans le tableau', verbose_name='Visible')),
                ('width', models.CharField(blank=True, help_text="Largeur de la colonne (ex: '150px')", max_length=50, null=True, verbose_name='Width')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le tableau", verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(help_text="Tableau auquel appartient cette configuration d'en-tête", on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='header_configs.tableconfig', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Header Configuration',
                'verbose_name_plural': 'Header Configurations',
                'unique_together': {('table', 'key')},
            },
        ),
    ]
